right_format = """
level \
$shlvl
at \
$shell
on \
${custom.arch}
"""

[character]
success_symbol = '[❯](bold blue)'

[custom.arch]
command = 'uname -m'
when = true

[shell]
disabled = false
fish_indicator = 'fish'
style = 'bold blue'

[shlvl]
disabled = false
symbol = ''
threshold = 1

[git_branch]
symbol = '󰘬 '

[git_metrics]
disabled = false

[nix_shell]
symbol = ' '

