format = """
$all\
$line_break\
${custom.arch}\
[|](bold blue) \
$shell\
[|](bold blue) \
$shlvl\
$character
"""

[character]
success_symbol = "[❯](bold blue)"

[custom.arch]
command = "uname -m"
style = "bold white"
when = true

[shell]
disabled = false

[shlvl]
disabled = false
symbol = ""
threshold = 1
style = "bold white"

[git_branch]
symbol = "󰘬 "

[git_metrics]
disabled = false

[nix_shell]
symbol = " "

