"$schema" = 'https://starship.rs/config-schema.json'

format = """
$all\
$line_break\
$custom\
$character
"""

[character]
success_symbol = '[❯](bold blue)'

[git_branch]
symbol = '󰘬 '

[git_metrics]
disabled = false

[memory_usage]
disabled = false
threshold = -1
format = '$symbol[${ram} \[${ram_pct}\] ]($style)'

[custom.arch]
command = 'uname -m'
when = true
style = 'bold blue'
