name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Check flake
        run: nix flake check
      - name: Check formatting and Linting
        run: nix fmt -- --ci
      - name: Build flake
        run: nix build .#darwinConfigurations."s3igo@mbp2023".system
