cursor = '▇'
blinking-cursor = false
ignore_theme_selection_fg_color = false
performance = 'High'
option-as-alt = 'both'

[window]
mode = 'Maximized'

[background]
mode = 'Color'
opacity = 0.5 # not working

[fonts]
family = 'UDEV Gothic NFLG'
size = 19
shell = { program = '/bin/zsh', args = ['-l', '-c', 'tmux attach || tmux attach -t 0 || tmux'] } # not working

