[note]
filename = "{{date now '%Y%m%d%H%M%S'}}"

[group.journal.note]
filename = "{{date now '%Y-%m-%d'}}"

[filter]
journal = "--sort created journal"

[alias]
edit-last = "zk edit --limit 1 --sort modified- $@"
journal = 'zk new --no-input "${ZK_NOTEBOOK_DIR}/journal"'

# [tool]
# fzf-preview = "bat -p --color always {-1}"
