shell = "zsh"
apply = ["defer"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins.compinit]
inline = "autoload -Uz compinit && compinit"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ['{{ name }}.zsh']

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"

[plugins.undollar]
github = "zpm-zsh/undollar"

[plugins.atuin]
github = 'atuinsh/atuin'

[plugins.direnv]
inline = 'type direnv > /dev/null 2>&1 && eval "$(direnv hook zsh)"'

[plugins.starship]
inline = 'type starship > /dev/null 2>&1 && eval "$(starship init zsh)"'

[plugins.github]
inline = 'type gh > /dev/null 2>&1 && eval "$(gh completion -s zsh)"'

[plugins.zoxide]
inline = '''
declare -x _ZO_DATA_DIR="${XDG_DATA_HOME}/zoxide"
type zoxide > /dev/null 2>&1 && eval "$(zoxide init zsh)"
'''

[plugins.local]
local = "~/.dotfiles/config/common/shell"
use = ["*.zsh", "*.sh"]
apply = ["source"]
