[note]
filename = "{{format-date now '%Y%m%d%H%M%S'}}"

[group.journal.note]
filename = "{{format-date now '%Y-%m-%d'}}"

[group.post.note]
filename = "{{slug title}}"

[filter]
notes = "-f oneline -x journal"

[alias]
edit-last = "zk edit --limit 1 --sort modified- $@"
journal = 'zk new --no-input "${ZK_NOTEBOOK_DIR}/journal"'

[tool]
fzf-preview = "bat -p --color always {-1}"
